### PR TITLE
Fix empty password using interactive shell

### PR DESCRIPTION
**Pull request by boekkooi**
This PR fixes a problem where a empty password triggers the mysql commands to request the password

### CODE REVIEW

**Comment by boekkooi** [comment]
@vipsoft @robocoder Any chance to get this merged because the bundle is unusable on travis

**Comment by robocoder** [comment]
I would prefer `strlen` over `!empty`.

**Comment by boekkooi** [comment]
@robocoder Fixed

**Comment by boekkooi** [comment]
@robocoder Thanks!

**Pull request merged**
